default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: admin
  host: localhost
  port: 5432
  database: shoptest

development:
  <<: *default
  database: shoptest

test:
  <<: *default
  database: shoptest

